server:
  port: 8081

spring:
  application:
    name: 'syscontrol-service'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://49.235.184.142:3306/study1?characterEncoding=utf-8&autoReconnect=true&useSSL=false&serverTimezone=Hongkong
    username: study1
    password: study1

# dubbo 相关配置(dubbo 的配置不再以 Spring 开头)
dubbo:
  application:
    # 应用名称
    name: ${spring.application.name}
  protocol:
    # 协议端口
    port: 20880
    # 协议名称 默认使用协议为dubbo协议
    name: dubbo
  # 注册中心信息
  registry:
    address: zookeeper://127.0.0.1:2181
    # 默认组
    group: dubbo
#  # 元数据中心
#  metadata-report:
#    address: zookeeper://127.0.0.1:2181
  provider:
    protocol: dubbo
    version: 1.0.0
    # 服务请求可以在指定时间内完成，指定时间内未完成立即失败
    # 10秒
    timeout: 10000
  scan:
    # 接口实现者（服务实现）包
    base-packages: com.demofactory.syscontrol.service


mybatis-plus:
  global-config:
    # 是否控制台 print mybatis-plus 的 LOGO
    banner: true
  type-aliases-package: com.demofactory.syscontrol.domain
  configuration:
    # 自动驼峰命名规则 默认true 如果您的数据库命名符合规则无需使用 @TableField 注解指定数据库字段名
    map-underscore-to-camel-case: true
    # Mybatis一级缓存，默认为 SESSION
    local-cache-scope: session
    # 开启Mybatis二级缓存，默认为 true
    cache-enabled: true
    # sql打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
